export type DisputeStatus = "Not Started" | "In Review" | "Submitted" | "Resolved";

export type DeductionRecord = {
  id: string;
  distributor: string;
  retailer: string;
  invoiceNumber: string;
  deductionCode: string;
  deductionType: string;
  reason: string;
  amount: number;
  date: string;
  flagged: boolean;
  disputeStatus: DisputeStatus;
};

export const deductionRows: DeductionRecord[] = [
  {
    id: "d-1001",
    distributor: "UNFI",
    retailer: "Whole Foods",
    invoiceNumber: "INV-48211",
    deductionCode: "PRICING",
    deductionType: "Pricing",
    reason: "Invoice price exceeded contracted list cost.",
    amount: 3285.14,
    date: "2026-04-28",
    flagged: true,
    disputeStatus: "In Review",
  },
  {
    id: "d-1002",
    distributor: "KeHE",
    retailer: "Target",
    invoiceNumber: "INV-48212",
    deductionCode: "SHORTAGE",
    deductionType: "Shortage",
    reason: "Retailer reported 4-case short shipment.",
    amount: 186.5,
    date: "2026-04-27",
    flagged: false,
    disputeStatus: "Not Started",
  },
  {
    id: "d-1003",
    distributor: "Amazon",
    retailer: "Kroger",
    invoiceNumber: "INV-48213",
    deductionCode: "COMPLIANCE",
    deductionType: "Compliance",
    reason: "ASN detail mismatch with received pallet labels.",
    amount: 975.24,
    date: "2026-04-27",
    flagged: true,
    disputeStatus: "Submitted",
  },
  {
    id: "d-1004",
    distributor: "Faire",
    retailer: "Sprouts",
    invoiceNumber: "INV-48214",
    deductionCode: "PROMO",
    deductionType: "Promotional",
    reason: "Promo allowance claimed above approved rate.",
    amount: 542.18,
    date: "2026-04-26",
    flagged: false,
    disputeStatus: "Not Started",
  },
  {
    id: "d-1005",
    distributor: "UNFI",
    retailer: "Publix",
    invoiceNumber: "INV-48215",
    deductionCode: "SHORTAGE",
    deductionType: "Shortage",
    reason: "2 cartons short on proof of delivery.",
    amount: 74.22,
    date: "2026-04-26",
    flagged: false,
    disputeStatus: "Resolved",
  },
  {
    id: "d-1006",
    distributor: "KeHE",
    retailer: "Whole Foods",
    invoiceNumber: "INV-48216",
    deductionCode: "PRICING",
    deductionType: "Pricing",
    reason: "Temporary price reduction billed outside promo window.",
    amount: 1520.67,
    date: "2026-04-25",
    flagged: true,
    disputeStatus: "In Review",
  },
  {
    id: "d-1007",
    distributor: "Amazon",
    retailer: "Amazon Fresh",
    invoiceNumber: "INV-48217",
    deductionCode: "FREIGHT",
    deductionType: "Freight",
    reason: "Chargeback for late delivery appointment.",
    amount: 318.0,
    date: "2026-04-25",
    flagged: false,
    disputeStatus: "Submitted",
  },
  {
    id: "d-1008",
    distributor: "Faire",
    retailer: "Target",
    invoiceNumber: "INV-48218",
    deductionCode: "COMPLIANCE",
    deductionType: "Compliance",
    reason: "Missing lot code on outer case labels.",
    amount: 1268.4,
    date: "2026-04-24",
    flagged: true,
    disputeStatus: "In Review",
  },
  {
    id: "d-1009",
    distributor: "UNFI",
    retailer: "Kroger",
    invoiceNumber: "INV-48219",
    deductionCode: "PROMO",
    deductionType: "Promotional",
    reason: "Off-invoice promo accrual not matching contract.",
    amount: 462.87,
    date: "2026-04-24",
    flagged: false,
    disputeStatus: "Not Started",
  },
  {
    id: "d-1010",
    distributor: "KeHE",
    retailer: "Safeway",
    invoiceNumber: "INV-48220",
    deductionCode: "DAMAGE",
    deductionType: "Returns",
    reason: "Store claimed damaged units on arrival.",
    amount: 221.09,
    date: "2026-04-23",
    flagged: false,
    disputeStatus: "Resolved",
  },
  {
    id: "d-1011",
    distributor: "Amazon",
    retailer: "Walmart",
    invoiceNumber: "INV-48221",
    deductionCode: "PRICING",
    deductionType: "Pricing",
    reason: "EDI price file update not reflected at ship date.",
    amount: 4875.33,
    date: "2026-04-23",
    flagged: true,
    disputeStatus: "Submitted",
  },
  {
    id: "d-1012",
    distributor: "Faire",
    retailer: "Sprouts",
    invoiceNumber: "INV-48222",
    deductionCode: "SHORTAGE",
    deductionType: "Shortage",
    reason: "Retailer shortage claim pending POD reconciliation.",
    amount: 95.16,
    date: "2026-04-22",
    flagged: false,
    disputeStatus: "Not Started",
  },
  {
    id: "d-1013",
    distributor: "UNFI",
    retailer: "Costco",
    invoiceNumber: "INV-48223",
    deductionCode: "COMPLIANCE",
    deductionType: "Compliance",
    reason: "Pallet height exceeded compliance specification.",
    amount: 2640.0,
    date: "2026-04-22",
    flagged: true,
    disputeStatus: "In Review",
  },
  {
    id: "d-1014",
    distributor: "KeHE",
    retailer: "Whole Foods",
    invoiceNumber: "INV-48224",
    deductionCode: "PROMO",
    deductionType: "Promotional",
    reason: "Retail ad event funded at incorrect rate.",
    amount: 688.21,
    date: "2026-04-21",
    flagged: false,
    disputeStatus: "Submitted",
  },
  {
    id: "d-1015",
    distributor: "Amazon",
    retailer: "Target",
    invoiceNumber: "INV-48225",
    deductionCode: "FREIGHT",
    deductionType: "Freight",
    reason: "Detention charge deducted from settlement.",
    amount: 129.99,
    date: "2026-04-21",
    flagged: false,
    disputeStatus: "Resolved",
  },
  {
    id: "d-1016",
    distributor: "Faire",
    retailer: "Kroger",
    invoiceNumber: "INV-48226",
    deductionCode: "PRICING",
    deductionType: "Pricing",
    reason: "Allowance already applied but deducted again.",
    amount: 1744.66,
    date: "2026-04-20",
    flagged: true,
    disputeStatus: "In Review",
  },
  {
    id: "d-1017",
    distributor: "UNFI",
    retailer: "Whole Foods",
    invoiceNumber: "INV-48227",
    deductionCode: "SHORTAGE",
    deductionType: "Shortage",
    reason: "Case quantity dispute on mixed pallet receipt.",
    amount: 58.47,
    date: "2026-04-20",
    flagged: false,
    disputeStatus: "Not Started",
  },
  {
    id: "d-1018",
    distributor: "KeHE",
    retailer: "Publix",
    invoiceNumber: "INV-48228",
    deductionCode: "COMPLIANCE",
    deductionType: "Compliance",
    reason: "Missing expiration date on shelf-ready packaging.",
    amount: 1120.78,
    date: "2026-04-19",
    flagged: true,
    disputeStatus: "Submitted",
  },
  {
    id: "d-1019",
    distributor: "Amazon",
    retailer: "Safeway",
    invoiceNumber: "INV-48229",
    deductionCode: "PROMO",
    deductionType: "Promotional",
    reason: "Promo billback duplicated in weekly statement.",
    amount: 338.62,
    date: "2026-04-19",
    flagged: false,
    disputeStatus: "Resolved",
  },
  {
    id: "d-1020",
    distributor: "Faire",
    retailer: "Costco",
    invoiceNumber: "INV-48230",
    deductionCode: "DAMAGE",
    deductionType: "Returns",
    reason: "Damaged display units returned to DC.",
    amount: 2815.5,
    date: "2026-04-18",
    flagged: true,
    disputeStatus: "In Review",
  },
  {
    id: "d-1021",
    distributor: "UNFI",
    retailer: "Target",
    invoiceNumber: "INV-48231",
    deductionCode: "PRICING",
    deductionType: "Pricing",
    reason: "Net price discrepancy against approved quote.",
    amount: 905.41,
    date: "2026-04-18",
    flagged: false,
    disputeStatus: "Submitted",
  },
  {
    id: "d-1022",
    distributor: "KeHE",
    retailer: "Kroger",
    invoiceNumber: "INV-48232",
    deductionCode: "SHORTAGE",
    deductionType: "Shortage",
    reason: "Short shipment claim under DC receiving tolerance.",
    amount: 42.33,
    date: "2026-04-17",
    flagged: false,
    disputeStatus: "Not Started",
  },
  {
    id: "d-1023",
    distributor: "Amazon",
    retailer: "Whole Foods",
    invoiceNumber: "INV-48233",
    deductionCode: "COMPLIANCE",
    deductionType: "Compliance",
    reason: "Routing guide non-compliance chargeback.",
    amount: 1965.22,
    date: "2026-04-17",
    flagged: true,
    disputeStatus: "In Review",
  },
  {
    id: "d-1024",
    distributor: "Faire",
    retailer: "Publix",
    invoiceNumber: "INV-48234",
    deductionCode: "PROMO",
    deductionType: "Promotional",
    reason: "Promo markdown deducted outside authorized SKUs.",
    amount: 517.49,
    date: "2026-04-16",
    flagged: false,
    disputeStatus: "Resolved",
  },
  {
    id: "d-1025",
    distributor: "UNFI",
    retailer: "Sprouts",
    invoiceNumber: "INV-48235",
    deductionCode: "FREIGHT",
    deductionType: "Freight",
    reason: "Fuel surcharge backcharge from freight settlement.",
    amount: 277.18,
    date: "2026-04-16",
    flagged: false,
    disputeStatus: "Submitted",
  },
  {
    id: "d-1026",
    distributor: "KeHE",
    retailer: "Target",
    invoiceNumber: "INV-48236",
    deductionCode: "DAMAGE",
    deductionType: "Returns",
    reason: "Warehouse handling damage reported at intake.",
    amount: 3495.76,
    date: "2026-04-15",
    flagged: true,
    disputeStatus: "In Review",
  },
];
